name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Actualizado a v4
      
      - uses: actions/setup-node@v4  # Actualizado a v4
        with:
          node-version: 20  # Recomendado usar Node 20 ahora
          
      - run: npm install
      - run: npm run build
      
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/deploy-pages@v3  # Actualizado a v3